# Cargo configuration for the chess engine

# Build settings
[build]
# Parallel compilation for faster builds
jobs = 0  # Use all available cores

# Development profile with faster compilation and debugging
[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true

# Release profile with maximum optimization
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true